### ISSUE TITLE
Live stream

### ISSUE THREAD

**Issue by dromicron** [hyugogirubato/pydash2hls#2]
Possible to support live stream in DASH (mpd) and output to live HLS ?

**Comment by hyugogirubato** [comment]
@dromicron 
I don't see how to integrate the live streaming of a dash file since the program is based on the parsing of a fixed dash file (which does not evolve).

**Comment by frzr** [comment]
ca fonctionne pas sur mon url mpd

**Comment by hyugogirubato** [comment]
@frzr 
Mmm er bien si ça ne fonctionne pas tu pourrais me dire comment récupère un URL mpd similaire au tien afin que je puisse aussi faire des tests et corriger le problème
